-----------

**Disciplina:** Introdução ao Aprendizado Profundo

**PPGEP UFF - 2024.2**

**Professor:** Diogo Ferreira de Lima Silva

-----------


# Tensors

O conceito de tensor pode ser descrito como uma generalização de matrizes e vetores.

A principal biblioteca de **deep learning** utiliza esse conceito, que traz eficiencia e rapidez ao treinamento dos modelos.

In [2]:
import torch
import numpy as np

### Escalares

In [3]:
a=10 # Atribuindo um escalar a uma variável em python
b=np.array(10.) # Usando numpy
c=torch.tensor(10.) # Usando torch

print(a) # escalar em python
print(b) # escalar no numpy
print(c) # um escalar pode ser visto como um tensor de rank 0 no torch


10
10.0
tensor(10.)


In [4]:
print(c.shape) # o shape vazio indica que é um escalar
print(c.ndim) # ndim retorna diretamente o rank do tensor

torch.Size([])
0


### Vetores

In [5]:
a=[10., 20., 30., 40., 50.] # lista no python
b= np.array([10., 20., 30., 40., 50.]) # vetor no numpy
c=torch.tensor([10., 20., 30., 40., 50.]) # vetor no torch (tensor de rank 1)


print(a) # escalar em python
print(b) # escalar no numpy
print(c) # um escalar pode ser visto como um tensor de rank 0 no torch

[10.0, 20.0, 30.0, 40.0, 50.0]
[10. 20. 30. 40. 50.]
tensor([10., 20., 30., 40., 50.])


In [6]:
print(c.shape) # Agora, o shape retornará o número de elementos do vetor!
print(c.ndim) # ndim retorna diretamente o rank do tensor

torch.Size([5])
1


### Matrizes 

In [7]:
a=[[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]] # lista de listas no python
b= np.array([[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]]) # matriz no numpy é um array de duas dimensões
c=torch.tensor([[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]]) # matriz no torch (tensor de rank 2)

print(a) # escalar em python
print(b) # escalar no numpy
print(c) # um escalar pode ser visto como um tensor de rank 0 no torch

[[10.0, 20.0, 30.0, 40.0, 50.0], [0.0, 5.0, 10.0, 15.0, 20.0]]
[[10. 20. 30. 40. 50.]
 [ 0.  5. 10. 15. 20.]]
tensor([[10., 20., 30., 40., 50.],
        [ 0.,  5., 10., 15., 20.]])


In [8]:
print(c.shape) # Agora, o shape indica que temos duas linhas e 5 colunas!
print(c.ndim) # ndim retorna diretamente o rank do tensor. Uma matriz é um tensor de rank 2

torch.Size([2, 5])
2


### Um container de duas Matrizes 

In [9]:
a=[[[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]], [[100., 200., 300., 400., 500.], [0., -5., -10., -15., -20.]]] # lista de listas de listas no python
b= np.array([[[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]], [[100., 200., 300., 400., 500.], [0., -5., -10., -15., -20.]]]) # array de três dimensões
c=torch.tensor([[[10., 20., 30., 40., 50.], [0., 5., 10., 15., 20.]], [[100., 200., 300., 400., 500.], [0., -5., -10., -15., -20.]]]) # tensor de de rank 3

print(a) # escalar em python
print(b) # escalar no numpy
print(c) # um escalar pode ser visto como um tensor de rank 0 no torch

[[[10.0, 20.0, 30.0, 40.0, 50.0], [0.0, 5.0, 10.0, 15.0, 20.0]], [[100.0, 200.0, 300.0, 400.0, 500.0], [0.0, -5.0, -10.0, -15.0, -20.0]]]
[[[ 10.  20.  30.  40.  50.]
  [  0.   5.  10.  15.  20.]]

 [[100. 200. 300. 400. 500.]
  [  0.  -5. -10. -15. -20.]]]
tensor([[[ 10.,  20.,  30.,  40.,  50.],
         [  0.,   5.,  10.,  15.,  20.]],

        [[100., 200., 300., 400., 500.],
         [  0.,  -5., -10., -15., -20.]]])


In [10]:
print(c.shape) # Temos 2 matrizes no formato 2X5
print(c.ndim) # ndim retorna diretamente o rank do tensor. Uma matriz é um tensor de rank 2

torch.Size([2, 2, 5])
3


## Alguns Métodos 

In [11]:
print(c.dtype) # tipo de dado do tensor

print("---------------------------")
# criando um tensor a partir de um array
b_tensor = torch.from_numpy(b) 
print(b_tensor)
print(b_tensor.dtype)
print("---------------------------")


# Mudando o tipo de dado de um tensor
b_tensor = b_tensor.to(torch.float32)
print(b_tensor)
print(b_tensor.dtype)
print("---------------------------")


torch.float32
---------------------------
tensor([[[ 10.,  20.,  30.,  40.,  50.],
         [  0.,   5.,  10.,  15.,  20.]],

        [[100., 200., 300., 400., 500.],
         [  0.,  -5., -10., -15., -20.]]], dtype=torch.float64)
torch.float64
---------------------------
tensor([[[ 10.,  20.,  30.,  40.,  50.],
         [  0.,   5.,  10.,  15.,  20.]],

        [[100., 200., 300., 400., 500.],
         [  0.,  -5., -10., -15., -20.]]])
torch.float32
---------------------------


Observação: é considerada boa prática trabalhar com float32 em deep learning por ganhos de eficiência e armazenamento.

In [12]:
M1 = torch.tensor([[1,2,3,4,5], [6,7,8,9,10]])
print(M1)
print("---------------------------")

# Transposta
print(M1.T)
print("---------------------------")

M2 = torch.tensor([[1,1],[2,2],[3,3],[4,4],[5,5]])
print(M2)
print("---------------------------")


# Multiplicação de matrizes
M3 = M1.matmul(M2)
print(M3)
print("---------------------------")


M4 = torch.tensor([2,2,2,2,2])
print(M4)
print("---------------------------")
M5 = torch.tensor([2,2])
print(M5)
print("---------------------------")

# broadcasting
print(M1.matmul(M4))
print(M1.T.matmul(M5))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
---------------------------
tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])
---------------------------
tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])
---------------------------
tensor([[ 55,  55],
        [130, 130]])
---------------------------
tensor([2, 2, 2, 2, 2])
---------------------------
tensor([2, 2])
---------------------------
tensor([30, 80])
tensor([14, 18, 22, 26, 30])


In [13]:
print(torch.zeros(10,2))
print("---------------------------")

print(torch.ones(10,2))
print("---------------------------")

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
---------------------------
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
---------------------------


Empilhando tensores

In [14]:
a = torch.tensor([2,2])
b = torch.ones(2)


c = torch.stack((a,b))
print(torch.stack((a,b)))
print("---------------------------")

d = torch.stack((a,b, torch.tensor([3,3])))
print(d)

tensor([[2., 2.],
        [1., 1.]])
---------------------------
tensor([[2., 2.],
        [1., 1.],
        [3., 3.]])


In [15]:
print(torch.stack((d,d)))

tensor([[[2., 2.],
         [1., 1.],
         [3., 3.]],

        [[2., 2.],
         [1., 1.],
         [3., 3.]]])
